// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHy-_xMl4lpXb5YwJmoSynU3mpw_GsD2Y',
    appId: '1:200806954770:android:28aefde9452edb4b0425cb',
    messagingSenderId: '200806954770',
    projectId: 'ws-portail-sup',
    storageBucket: 'ws-portail-sup.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHy-_xMl4lpXb5YwJmoSynU3mpw_GsD2Y',
    appId: '1:200806954770:android:28aefde9452edb4b0425cb',
    messagingSenderId: '200806954770',
    projectId: 'ws-portail-sup',
    storageBucket: 'ws-portail-sup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAbe33jeyEZmVJdhm5W12Xu16jeipgOCw',
    appId: '1:200806954770:ios:a041bde6a8a3a6560425cb',
    messagingSenderId: '200806954770',
    projectId: 'ws-portail-sup',
    storageBucket: 'ws-portail-sup.appspot.com',
    iosBundleId: 'com.sitaninfo.wssupportailapp',
  );
}
