// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG648KzkSgUjYiaodfzPSsVTwARfFj1_g',
    appId: '1:1022120905950:web:c3455a77b7aede37b5464f',
    messagingSenderId: '1022120905950',
    projectId: 'ws-portail-sec-e18ab',
    authDomain: 'ws-portail-sec-e18ab.firebaseapp.com',
    storageBucket: 'ws-portail-sec-e18ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqY-xN70lUNIBX9rfE6zD4HFg_BPwyLY',
    appId: '1:1022120905950:android:cb5ca72306c3c1c8b5464f',
    messagingSenderId: '1022120905950',
    projectId: 'ws-portail-sec-e18ab',
    storageBucket: 'ws-portail-sec-e18ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsn_GF0do2i8bXpILNK02Fsww_qfe2dVQ',
    appId: '1:1022120905950:ios:452eb1d098c4882fb5464f',
    messagingSenderId: '1022120905950',
    projectId: 'ws-portail-sec-e18ab',
    storageBucket: 'ws-portail-sec-e18ab.appspot.com',
    iosBundleId: 'com.example.myWebschoolSec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsn_GF0do2i8bXpILNK02Fsww_qfe2dVQ',
    appId: '1:1022120905950:ios:452eb1d098c4882fb5464f',
    messagingSenderId: '1022120905950',
    projectId: 'ws-portail-sec-e18ab',
    storageBucket: 'ws-portail-sec-e18ab.appspot.com',
    iosBundleId: 'com.example.myWebschoolSec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG648KzkSgUjYiaodfzPSsVTwARfFj1_g',
    appId: '1:1022120905950:web:c3455a77b7aede37b5464f',
    messagingSenderId: '1022120905950',
    projectId: 'ws-portail-sec-e18ab',
    authDomain: 'ws-portail-sec-e18ab.firebaseapp.com',
    storageBucket: 'ws-portail-sec-e18ab.appspot.com',
  );
}
